### ISSUE TITLE
Caption to images

### ISSUE THREAD

**Issue by schoeller** [Karmalakas/grav-plugin-photoswipe#15]
Dear all,

thanks for the work.
I am looking for a recipe to add and display caption information to images. I'll try for starters to add exif information.

Best regards

Sebastian

**Comment by Karmalakas** [comment]
Hi, and thanks for the feedback
Did you try adding a caption and it didn't work? From the _readme_:
> Every item also may have `data-caption` attribute or, if you use `<figure></figure>` markdown, you can have `<figcaption>` in it.

**Comment by schoeller** [comment]
Cheers for the prompt answer. I would like to embedd info in the image (for example EXIF title tag) and read that to display as caption. 

Am 20. Februar 2024 08:33:16 MEZ schrieb Karmalakas ***@***.***>:

**Comment by Karmalakas** [comment]
Maybe I'm misunderstanding something, but I don't think I would add EXIF data reading to this plugin. I believe there are some other plugins for that purpose. Maybe that could be used to extract the data and save it on Grav as a caption for your images and then use that to add a caption to Photoswipe plugin 🤔

**Comment by schoeller** [comment]
Have added the plugin `bin/gpm install admin-addon-media-metadata`. This add the `meta.yaml` files when required and now I can call `{{ item.meta.title|e }}` from templates. Will crawl further in order to achieve what I desire. Sorry to have bothered.
