### ISSUE TITLE
A simple request for clarification about syntax

### ISSUE THREAD

**Issue by ventoux84** [Karmalakas/grav-plugin-photoswipe#16]
Hello,
I want to create a slideshow with a caption for each photo using grav-plugin-photoswipe.

I've read the "usage" paragraph, but I can't figure out how to use the caption function and what its exact syntax is.
If i use 
`<figure> <img src="{{ item.cropResize(300, 150).url|e }}" alt=""/><figcaption>caption</figcaption></figure>`
All images have "caption" .
Can someone explain how to display its "title" and/or "caption" below each image? 

I've installed the "Admin Addon Media Metadata" plugin and used it to enter image titles and captions. All images also have their own xx.jpg.meta.yaml file.

**Comment by ventoux84** [comment]
I tried with
` <figure> <img src="{{ item.cropResize(300, 150).url|e }}" alt=""/><figcaption>{{ item.title}} {{ item.caption}}</figcaption></figure>`
It works, but thumbnail are displayed in list, not in mosaic . What does i miss ?

**Comment by Karmalakas** [comment]
Hi @ventoux84, glad you figured out how to add captions, but this plugin only takes care of the photoswipe part and doesn't add or change any thumbnail list styles. You also can see the same behavior on [this demo page](https://www.karmalakas.lt/grav-plugins-demos/photoswipe). You need to style it yourself as you see fit

**Comment by ventoux84** [comment]
Thanks for your reply and this plugin.
What i call mosaic, is what is shown in your demo. With my code, i get every  thumbnail arranged one below the other, and no one next to the other.

**Comment by Karmalakas** [comment]
On my demo page I use `<a>` tags for items, which are inline, so they are shown next to each other. `<figure>` is a block element, hence each item on a new row

**Comment by ventoux84** [comment]
Ah! Thanks, I'm learning things.
I'll try with a and caption

Edit : It works !   re re re thanks very much for your help.

**Comment by ventoux84** [comment]
The further you go, the more you want.
Is it possible to display "Title" on the page with thumbnails, and "Caption" on the full image ?

**Comment by Karmalakas** [comment]
> Is it possible to display "Title" on the page with thumbnails

Yes, but that's maybe better to ask on [Grav forum](https://discourse.getgrav.org/). Just make sure to check [posting guidelines](https://discourse.getgrav.org/t/welcome-to-the-grav-cms-community-forums/8) 


> and "Caption" on the full image

Not sure I understand. Do you mean when photoswipe opens and shows an image? I believe you can edit your own styles there too and position the caption where you want

**Comment by ventoux84** [comment]
Done with 
```
 <a href="{{ item.url|e }}" class="gallery-item" data-size="{{ item.width ~ 'x' ~ item.height }}" caption="{{ item.title}}">
             <img src="{{ item.cropResize(300, 150).url|e }}" alt="" /><figcaption>{{ item.caption}}</figcaption>
        </a>
```

**Comment by ventoux84** [comment]
Thanks for all.

**Comment by Karmalakas** [comment]
I don't think `figcaption` is valid inside the `a`. Remove it and change `caption` attribute to `data-caption`, as mentioned in the README

**Comment by ventoux84** [comment]
What works to do what I want is
```
{{ photoswipe('photoswipe-gallery-id', 'a') }}

<div id="photoswipe-gallery-id">
    {% for item in page.media.images %}
     <a href="{{ item.url|e }}" class="gallery-item" data-size="{{ item.width ~ 'x' ~ item.height }}" data-caption="{{item.caption}}">
             <img src="{{ item.cropResize(300, 150).url|e }}" alt="" />{{item.title}}
    </a>
    {% endfor %}
</div>
```
And no, it only works on the first access, if i reload the page i get a list and no a mosaic and the slideshow is broken.

**Comment by Karmalakas** [comment]
Are you using this in a modal page? If so, please check [this thread](https://github.com/Karmalakas/grav-plugin-photoswipe/issues/1)

**Comment by ventoux84** [comment]
No, it's not a modular page, just a "default".
But yes, with "never_cache_twig: true " the page can be reloaded several time and is always well displayed.

I tested with the code of your readme.md and it's the same behavior.
