### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by ventoux84** [Karmalakas/grav-plugin-photoswipe#17]
Hello,
I want to protect images with .htaccess and .htpassword.
If i put the .htaccess file into the page's directory, full size image are well protected by password;  but all thumbnails are displayed anyway. 

Do you know a way to protect full images and also thumbnails ?
Perhaps by placing the images in an other directory ? But is it possible to indicate a path in 
` {% for item in page.media.images %}`

I specify that it is the same behavior using the "login" plugin. And more, the images can be downloaded by direct link.

**Comment by Karmalakas** [comment]
Sorry, but this is way out of the scope of the plugin. It doesn't care where images are located as long as there are correct thumb and full image paths provided in the template. I believe there was a similar discussion on Grav forum, try searching there maybe

**Comment by ventoux84** [comment]
>  ---. It doesn't care where images are located as long as there are correct thumb and full image paths provided in the template.---

How can i provide correct path for a directory different to the page directory  in ?
`{% for item in page.media.images %}`

**Comment by Karmalakas** [comment]
You can put your images pretty much anywhere in the user folder
Check [the docs](https://learn.getgrav.org/17/content/media#where-to-put-your-media-files)

**Comment by ventoux84** [comment]
Thanks, it works with
`{% for item in page.find('/xx').media  %}`
For media in /user/xx/ directory
