### ISSUE TITLE
A possible webp support?

### ISSUE THREAD

**Issue by 01Kuzma** [Karmalakas/grav-plugin-photoswipe#9]
Hello!
Did you try to integrate the `webp` support with the gallery?
At this moment this [grav webp plugin](https://github.com/greenrivers/grav-plugin-webp) supports image conversion into `webp` file format. 
`img` tags should be appended with these filters:
```
   <img alt="webp image" src="{{ '/user/images/my-image.jpg'|webp }}">
   <img alt="webp image" src="{{ url(logo)|webp }}">
```
It it possible to override the template to make such support? Or everything is done in `js` ?

P.S. it seems that the `photoswipe` library support `webp` file format [natively ](https://photoswipe.com/custom-content/) (but probably partially?)

Thank you!

**Comment by Karmalakas** [comment]
I believe you could easily extend main [plugin template](https://github.com/Karmalakas/grav-plugin-photoswipe/blob/main/templates/photoswipe.html.twig) by copying it to `/user/themes/[YOUR_THEME]/templates/photoswipe.html.twig` (you'd need some [custom theme](https://learn.getgrav.org/16/themes/customization#theme-inheritance)) and change `src` on line `13`. This should work

Most likely I will not implement this feature in the plugin itself, because it would add one more dependency and not many need this I assume 🤔

**Comment by 01Kuzma** [comment]
Thank you!
I will try this!
P.S. I presume it should be something like this: `<img src="{{ item.cropResize(500, 250).url|e|webp }}" alt=""/>`

**Comment by Karmalakas** [comment]
Probably yes. Would need to test with Webp plugin installed. Or maybe `|e` is not needed at all in such case

**Comment by 01Kuzma** [comment]
Just one question: are you sure that overridden template file should be placed here:  `/user/themes/[YOUR_THEME]/templates/photoswipe.html.twig` not in a deeper folder? As an example ` /user/themes/[YOUR_THEME]/templates/plugins/photoswipe/templates` or other folder ?
Now I'm experimenting with it and overridden twig template doesn't make any difference... ALready placed in different folders...

**Comment by Karmalakas** [comment]
Seems to be working fine for me 😕 
Try clearing caches
![image](https://user-images.githubusercontent.com/3602819/206256164-73dcf843-50d7-4f6b-9a43-d2371509b902.png)

**Comment by 01Kuzma** [comment]
Understood!
Thanks for tip ;)

**Comment by Karmalakas** [comment]
Did you manage to make it work? Just curious 🙂

**Comment by 01Kuzma** [comment]
Unfortunately no, I tried yesterday, but `webp` was not loaded...
I will try further to investigate it. The problem is that webp plugin doesn't work on my localhost, so it's harder to debug the problem
